### ISSUE TITLE
Mutual SSL Error message

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#1013]
### Describe your problem(s)

When mutual SSL is failed error we get is invalid access token. This error message should be improved.

### How will you implement it

---

**Comment by AmaliMatharaarachchi** [comment]
Error message 
```
{
    "fault": {
        "code": 900918,
        "message": "SSL handshake failure",
        "description": "SSL handshake failure. Make sure you correctly configured Mutual SSL"
    }
}
```

**Comment by praminda** [comment]
Looking at this from security perspective, I think we shouldn't give specific error messages for authentication failures. This should return generic authentication failure error so that client can't identify which part of auth process failed. Make sure to log the failure in detail so that admins can figure out whats going wrong.

**Comment by praminda** [comment]
It seems like message is ok but description should be generic. @ayomawdb any feedback?
