### ISSUE TITLE
Implement client-side support for fail-over/load-balance for microgateway analytics file uploading

### ISSUE THREAD

**Issue by chanakaudaya** [wso2/product-microgateway#1053]
### Describe your problem(s)
API Manager analytics minimum HA deployment requires 2 worker nodes to be deployed. In the current implementation of the MGW, users have to configure the file uploading endpoint in the micro-gw.conf file under the analytics section.
```
[analytics]
enable=true
uploadingTimeSpanInMillis=600000
uploadingEndpoint="https://localhost:9444/analytics/v1.0/usage/upload-file"
rotatingPeriod=600000
task.uploadFiles=true
username="admin"
password="admin"
```

In a scenario like above where we have 2 worker nodes receiving analytics events in active/passive or active/active mode, we need to configure an external load balancer to get APIM analytics working with MGW. 

### Describe your solution
It would have been much easier if the user can configure the URLs of worker nodes in the above configuration and the client does the fail-over/load-balancing instead of using an external LB.
```
uploadingEndpoint="https://localhost:9444/analytics/v1.0/usage/upload-file,https://localhost:9445/analytics/v1.0/usage/upload-file"
```

### How will you implement it
We already have this feature in the standard API gateway. We can use a similar approach to implement this.

**Comment by Rajith90** [comment]
The file uploading was done using https connection. So if there are n number of analytics servers, then file should go to only one analytics server. So basically in order to send data to  any cluster we need a LB. So this config url requires load balancer url if analytics cluster is present. We do not require client side load balancing since we are not using binary protocols like thrift.
