### ISSUE TITLE
APIs imported from APIM 3.0 and 3.1 should go to api_definitions

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#1079]
### Description:
Currently the APIs imported from APIM 3.0. and 3.1 are saved inside the gen/api_definitions folder. This is not required since we are not modifying the imported swagger from our end. We need to save APIM 2.x swagger in gen/api_definitions folder because we modified the swagger during the build process to add the wso2 specific extensions

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
If we allow or promote editing APIs imported from APIM, it will make APIs in MGW and normal GW to behave differently. Because after editing and saving/deploying API definition in APIM, you do another set of API level changes in MGW side. Which makes it a different API compared to whatever running in APIM GW. Any changes to the imported API should come from APIM side IMO.
