### ISSUE TITLE
Issue occurred when the response validation is enabled

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-microgateway#1125]
### Description:
There is an issue in the response validation flow.

### Steps to reproduce:
Enable validation config in micro-gw.conf
[validationConfig]
  enableRequestValidation = true 
  enableResponseValidation = true

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by VirajSalaka** [comment]
To reproduce the above issue, please follow the below steps.
create and build a microgateway project following the quick start guide. If the response validation is not enabled, the client receives the following response.
`{"code":1,"type":"error","message":"Pet not found"}`

When the response validation is enabled, the client receives the below error message instead of the actual one.
`json string can not be null or empty`

In the gateway, we can see the following log.
```
error: java.lang.IllegalArgumentException message=json string can not be null or empty
        at wso2.gateway.src.gateway.native.validator:jResponseValidate(/src/gateway/native/validator.bal:76)
           wso2.gateway.src.gateway.native.validator:responseValidate(/src/gateway/native/validator.bal:50)
           wso2.gateway.src.gateway.filters.validation_filter:doValidationFilterResponse(/src/gateway/filters/validation_filter.bal:124)
           wso2.gateway.ValidationFilter:filterResponse(/src/gateway/filters/validation_filter.bal:53)
           ballerina.http.Caller:respond(http_connection.bal:47)
           wso2.petstore__service_0:get65e93aad2bfc49afa93593bed81df5e7(Swagger_Petstore__1_0_3.bal:438)
```
