### ISSUE TITLE
Improvement to customize and generate backend JWT tokens within Microgateway

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/product-microgateway#1196]
### Describe your problem(s)
Currently the JWT token sent to back-end is included as a custom claim inside the authentication token. There should be a method to create JWT token within microgateway providing the ability for users to manipulate claims or the generation of the tokens.

### Describe your solution
We need to define a Abstract class including the basic generation and extending that the user can customize the token generation process or simply manipulate the claims as required.

### How will you implement it
Using ballerina interop capability to invoke the the user written or default token generator class.

---

**Comment by VirajSalaka** [comment]
So far, it is required to fix the following issues.

- {dialect}/tier claim should represent the subscription tier, not api tier
-  {dialect}/endUserTenantId property is not populated.
- Needs to bring in a common config location in the format of a record, So that the configuration values can be easily read.
- Needs to refactor code such that, the jwt generation flow follows a one path (regardless of whether it is jwt or opaque token) to give more simple view.

  -  Can try creating a decoded jwt:Payload similar structure in the opaque flow
