### ISSUE TITLE
Performance Results

### ISSUE THREAD

**Issue by chunyeow** [wso2/product-microgateway#1282]
### Description:
How the Apache JMeter interconnect with API Microgateway? Any optimization done over the machine running the API Microgateway? Referring to the following performance results: https://github.com/wso2/product-microgateway/blob/performance/300-general/performance/benchmarks/summary.md

**Comment by praminda** [comment]
@VirajSalaka @tharmini Can you provide any inputs on this?

**Comment by VirajSalaka** [comment]
Basically the test setup looks like this.
![Mgw_Perf_test](https://user-images.githubusercontent.com/17596317/84730603-4122df80-afb4-11ea-9a52-d732cb09d315.png)

When we need to test with "2x" concurrent users, each Jmeter server will handle "x" concurrent users. It is configured in this manner because handling large concurrent users (>= 500) by a single JMeter will not be ideal. 

We used a c5.xlarge instance for JMeter servers on this occasion. And the allocated heap size was 4G.

**Comment by Rajith90** [comment]
Answered, hence closing
