### ISSUE TITLE
JWT Revocation using the Traffic Manager Component

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1298]
### Describe your problem(s)
Under the current implementation, it is required to have an etcd server to persist the revoked JWT tokens. While keeping the same implementation, we could use the Traffic Manager Endpoint directly to retrieve persisted revoked tokens. In this case, persistence is handled by the Traffic Manager itself. 

In addition to that, the microgateway should have the ability to revoke tokens from any third party key manager. 

### Describe your solution
To revoke a certain token, the user can invoke the _/revoke_ endpoint of the microgateway or revoke the token from Key manager directly. Once it is revoked, the key manager is responsible for calling the notify endpoint of the microgateway. (There will be separate service running for this task within microgateway.) Then the microgateway will send that event to the traffic manager and traffic manager will store those revoked tokens. Finally, the traffic manager will publish a jms event under the relevant topic (_tokenRevocation_ ). As the microgateways are already subscribed to that topic, they will receive the event as well.

If the microgateway restarts, the set of revoked tokens should be fetched from the traffic manager. 

To check whether the provided token is revoked or not, the microgateway will use the _jti_ claim.

### How will you implement it
Please refer to the above segment additionally.
![Whiteboard 1 -01](https://user-images.githubusercontent.com/17596317/85520191-34d7fb80-b620-11ea-9242-948f7fa0ef08.png)

---
#### Suggested Labels:
Improvement

#### Suggested Assignees:
VirajSalaka

**Comment by Rajith90** [comment]
The above architecture was changed a bit. 
Now the /notify endpoint will not be exposed in the gateway/microgateway. It is moved to the Traffic manager component.
So when token get revoked in the key manager or STS it has to call the /notify endpoint of the traffic manager and notify about the revoked token. Most of the STS has this ability to call an extension in case of a revoked JWT.

Microgateway will connect with the traffic manager component during gateway startup and will fetch all the revoked tokens upto now. And the tokens that get revoked during the runtime will be notified by the traffic manager via topic subscription.
This capability is added with the PR : https://github.com/wso2/product-microgateway/pull/1328

Apart from this microgateway has the old mechanism also placed in order to handle revoked tokens. Where it can fetch revoked tokens from an etcd server during startup and get tokend revoked during gateway uptime via a topic subscription to ant message broker. So basically the STS or key manager has to put the revoked tokens into etcd server and the topic in order this flow to work.
