### ISSUE TITLE
Prevent router from crash loop back when started with no artefacts

### ISSUE THREAD

**Issue by mpmunasinghe** [wso2/product-microgateway#2618]
### Describe your problem(s)
When a router is stared without an artefact relevant to this particular partition it fails to activate the liveness probe. The partition creation happens based on a threshold configured and the lates partitions are not started with existing APIs. Hence, the partition router goes into a crash loop back until a API is allocated to the new partition. 

### Describe your solution
Enable the liveness probe based on the XDs connectivity to the API provider instead of the received XDs artefact from the upstream.

**Comment by VirajSalaka** [comment]
As per offline discussion had with @pubudu538 and @renuka-fernando , we decided to take the following approach. 

At the moment. the liveness probe and the readiness probe both remains the same. Instead of that we need to have two separate ways to distinguish them.

When the component successfully starts up we set the liveness probe. (regardless of whether APIs are available). And readiness probe will indicate when the APIs are available. Hence liveness probe would only tell if the component is up and running as a single entity, while readiness probe would indicate if the components are properly connected and it is in a state where it can serve as expected.

**Comment by mpmunasinghe** [comment]
> As per offline discussion had with @pubudu538 and @renuka-fernando , we decided to take the following approach.
> 
> At the moment. the liveness probe and the readiness probe both remains the same. Instead of that we need to have two separate ways to distinguish them.
> 
> When the component successfully starts up we set the liveness probe. (regardless of whether APIs are available). And readiness probe will indicate when the APIs are available. Hence liveness probe would only tell if the component is up and running as a single entity, while readiness probe would indicate if the components are properly connected and it is in a state where it can serve as expected.

LGTM

**Comment by VajiraPrabuddhaka** [comment]
As per the discussion with @pubudu538 @VirajSalaka @AmaliMatharaarachchi we decided to use the following approaches (steps) to fix this issue.
1. Separate out the readiness & liveness probes in GA according to the below criteria.

> Liveness : Check if the DB connection is successful and XDS port (XDS GRPC server) is up and running.
> Readiness : Will set as true, after the API artifacts are deployed to the XDS cache in the startup.

2. Send a empty snapshot from GA to LA (at the startup) when there are no APIs in GA for that particular LA label.

**Comment by VajiraPrabuddhaka** [comment]
closing with https://github.com/wso2/product-microgateway/pull/2785
