### ISSUE TITLE
Require a mechanism to receive updates on revoked tokens

### ISSUE THREAD

**Issue by nuwand** [wso2/product-microgateway#298]
**Description:**
When the Migrogateway is working with JWT formatted self-contained access tokens, it does not communicate with an STS for checking the validity of the token. It considers any token with a trusted signature as valid, as long as the token is not expired. This model becomes a problem when the respective token is revoked at the STS. There needs to be a mechanism where the Microgateway gets notified when a token is revoked before its expiry.

**Suggested Labels:**
feature

**Comment by nuwand** [comment]
I would suggest an approach to implement a pub-sub model where the STS and Microgateways are linked using a message broker. Whenever a token revoke request is received, the STS will publish a message to the broker. The broker will then propagate the message to the Microgateways. The Microgateways upon receiving this message will store the revoked tokens in-memory and treat them accordingly. The Microgateways should also save this information on a light-weight persistence layer so that the state is preserved and can be used upon restarts and new Microgateways joining the cluster of Microgateways. See image below.

![microgateway-token-revoke-architecture](https://user-images.githubusercontent.com/6469654/52628971-c5f07b80-2ede-11e9-88d8-e8cbef4c4863.png)

**Comment by CrowleyRajapakse** [comment]
The proposed approach has been reviewed and the following changes to the architecture were made. 

The new approach also will follow the pub-sub model where the STS and the Microgateways will be linked using a message broker. 

As for the lightweight persistent storage ETCD will be used since it is lightweight, already used in service discovery feature and can handle key expiry. 

Whenever a token request is received, the STS will publish a message to the message broker and also will store that revoked JWT’s JTI claim in the ETCD as well. 

Each time a new Mircogateway spins up it will pull all the revoked JTI list from the ETCD and store them in the cache. This only happens at the startup of the MG. 

Then the broker will propagate only the newly revoked JTI to the MG. Upon receiving the newly revoked JTI, it will also be stored in cache.

<img width="969" alt="jwt revoke feature" src="https://user-images.githubusercontent.com/23296184/53550825-afdcef00-3b5d-11e9-85fd-a1afef6388cb.png">

**Comment by sanjeewa-malalgoda** [comment]
Deploying ETCD just for the first time update retrieval process might not be good approach. If we are bringing message brocker and ETCD just to revoke tokens that is too much. Why do we need complete different run-time just to get this update. When OAuth scenario available microgateway need to connect with key manager server and it communicates via https. My suggestions is to use simple service call which serves revoked JTI list. We will not need to complicate deployment.

**Comment by Rajith90** [comment]
@sanjeewa-malalgoda , I think we do a http call to key manager for revoked list, then we have to do this call periodically from MGW side. If each MGW does this call to KM periodically then we will face scaling issues, because higher number of MGWs will send revoke token list request to the key manager.Which will cause scalability issues.

**Comment by pubudu538** [comment]
Due to the limitation explained by Rajith, one of the solutions is to move to a pub/sub approach. But the pub/sub approach cannot persist the previous tokens. When the gateways get restarted or a new gw comes, they need to know the already revoked tokens. In that case another option is to move the token persistent to some other layer. Due to some limitations in key manager it cannot persist. When the token is revoked, we remove the token from the token table to store that token in some other audit table. That table is not indexed allowing to do fast read/write to the table. Hence, we cannot expose an endpoint in key manager. If there are many tokens, it will take some time to load those data from the database.
Etcd is one of the options here to store the token.

**Comment by sanjeewa-malalgoda** [comment]
My suggestion was not to have periodic calls to key manager. When each gateway starts it need to call key manager and get list. Rest of the stuff handle bu pub/sub. Since gateway need to connect to topic in throttling case it can be there anyway. What i wanted was avoid adding new complexity to deployment. 

Where there is lot of tokens in revoked table we will anyway need to cleanup them. We will anyway have to read that table and put entries to ETCD.

**Comment by CrowleyRajapakse** [comment]
Creating a separate endpoint to get all the revoked token in the key manager would bind the micro-gateway solely with WSO2 api manager since providing a revoked token list isn't a default endpoint like /revoke /retrospection /token and won't be implemented by other api managers if not for a specific requirement. Thinking behind this was, by using a third party persistence storage like etcd would render this revocation function more general although it will add complexity to the deployment.

**Comment by sanjeewa-malalgoda** [comment]
Can you explain who put revoked tokens to ETCD in 3rd party key management solutions. I haven't heard any single oauth solution which provide such integration capability. So putting 3rd party persistence do not bring any advantage IMO.

**Comment by CrowleyRajapakse** [comment]
Revoked token has to store somewhere to refer for authentication purposes. Every key manager will have to store them in a database table. so they can use light weight persistence storages like etcd/redis instead of relational databases. 

When the token is revoked, we remove the token from the token table to store that token in the audit table. That table is not indexed allowing to do fast read/write to the table. so while removing and adding it to the audit table we also can add the revoked token to etcd. so that those revoked keys can be queried faster with the etcd by using all key retrieval endpoint. Since all revoked token retrieval happens on a startup of a Microgateway, it needs to happen without slowing down the spin up process. 

So we will have two storages containing revoked tokens, one for audit purposes in which token expiry and cleanup will not happen and will store these revoked tokens indefinitely. Other storage would be etcd in which  expired keys will be removed automatically. For example if JWT has the expiry time of 1 hour, etcd store would only have jwt's revoked in the last hour only.

if we are to remove etcd link, i think we have to create a database table which is indexed and store the revoked tokens and also have to implement key expiration scenario to that table. Then that table querying can be exposed through an endpoint in key manager. 

Since etcd is already implemented for service discovery feature in MG it would be an advantages to use etcd key querying endpoint and key expiration features instead of implementing them separately on key manager side according to my understanding.

**Comment by nuwand** [comment]
Have we thought of a way of getting all revoked JTIs from etcd when a MGW starts? Since etcd is a key value store, we need to know the key to get the values. Which means the MGW needs to know the keys to query for during startup.

**Comment by CrowleyRajapakse** [comment]
No, we can query all the keys in the etcd by using /keys endpoint without having to know any JTI, They response a json array with all the keys.

Ex:{"action":"get","node":{"dir":true,"nodes":[{"key":"/12a86fc7-ef77-45f5-ac81-c9753998a6e2","value":"true","modifiedIndex":20,"createdIndex":20},{"key":"/49d23442-7570-45b7-b14a-1c14ed7111e0","value":"true","modifiedIndex":25,"createdIndex":25},{"key":"/67f9aac0-e9f9-4052-acb2-7031b9da996d","value":"true","modifiedIndex":22,"createdIndex":22}]}}

we can extracted each key from this nodes json array and put in the cache.

**Comment by nuwand** [comment]
In that case we'll have to use an etcd that's dedicated to this particular use case only, which I don't think is feasible. Because a generic etcd will have a lot more than expired JTIs, which means if you query all of them you'll get a lot more keys than expired JTIs which are not relevant. Don't we have a way to prefix keys and query by whatever matches the prefix?

**Comment by CrowleyRajapakse** [comment]
We can create a directory named jti and store our revoked jti's in that directory only. Then the invoke url will be like http://127.0.0.1:2379/v2/keys/jti , it will list all the keys in jti directory. Sample response would be like,

Ex:{"action":"get","node":{"key":"/jti","dir":true,"nodes":[{"key":"/jti/10587fa9-9d4f-4990-9503-b6ff3498357b","value":"true","modifiedIndex":34,"createdIndex":34}],"modifiedIndex":33,"createdIndex":33}}

we can remove the /jti/ part by in the key by using substring function in ballerina.

Ex: int jtiLength = jtiWithSlashJTISlash.length();
      string jti = jtiWithSlash.substring(5, jtiLength);

**Comment by sanjeewa-malalgoda** [comment]
Let me add something,
We are not considering deployment complexities of adding another 3rd party component. If we see some issue with ETCD what we are going to do. Do we fork code? 

And regarding reading revoked token table we do not need to  read it for each and every call. We can keep copy of revoked tokens and send that response without querying database.

**Comment by malinthaprasan** [comment]
How about updating the above directory? Does it support adding/remove one entry without affecting others? Or do we need to PUT the whole directory at once?

**Comment by malinthaprasan** [comment]
@CrowleyRajapakse 

> Since etcd is already implemented for service discovery feature in MG it would be an advantages to use etcd key querying endpoint and key expiration features instead of implementing them separately on key manager side according to my understanding.

I beleive this does not mandate using etcd when using MGW in most cases?

**Comment by nuwand** [comment]
Functionality wise I don't see a big difference between using etcd or the API Manager itself for this purpose. What we somehow need is a revoked token registry to which the MG has access to. We can either use a dedicated registry for this like etcd, which would make the architecture more microservice friendly. Or we can implement the required functionality on the API Manager itself, which would be the monolith architecture pattern for solving the same problem. Each architecture pattern has their own pros and cons, which is not specific to this particular problem but generic across any software trying to weigh out the differences in each approach. So at the end of the day its just a choice we make understanding the pros and cons of whatever we choose.

**Comment by CrowleyRajapakse** [comment]
> How about updating the above directory? Does it support adding/remove one entry without affecting others? Or do we need to PUT the whole directory at once?

Yes, we can add and remove keys from the jti directory in etcd without any effect to other keys or to the directory. No need to put the whole directory at once with all the keys

**Comment by praminda** [comment]
Fixed with #420
