### ISSUE TITLE
Kubernetes artifact generation doesn't work

### ISSUE THREAD

**Issue by nuwanbando** [wso2/product-microgateway#520]
I am trying to generate K8 artifacts for my m-gw with - `https://github.com/nuwanbando/cnip-catalog/blob/master/gateways/wso2-micro-gw/passthrough/employees/conf/deployment-config.toml`

however I get,

`
Compiling source
    src:0.0.0
error: src:0.0.0::Swagger_Employees_1_0_0.bal:52:14: undefined field 'isBallerinaConf' in record 'ballerinax/kubernetes:0.0.0:FileConfig'
`

if I remove `isBallerinaConf` as its not part of Ballerina K8 annotation spec, I get a compilation error.

**Comment by Rajith90** [comment]
The issue is that "isBallerinaConf" is not supported with the config **[[kubernetes.kubernetesDeployment.copyFiles.files]]**. 
Please remove the below content  in your deployment-config.toml file

`
[kubernetes.kubernetesDeployment.copyFiles]
        enable = true
        [[kubernetes.kubernetesDeployment.copyFiles.files]]
            source = '/home/rajith/APIM/cli_restructure/wso2am-micro-gw-linux-3.0.0-beta3-SNAPSHOT/conf/micro-gw.conf'
            target = '/home/ballerina/conf/micro-gw.conf'
`

And specify the baseImage under the [kubernetes.kubernetesDeployment] as follows
`
baseImage = wso2/wso2micro-gw:3.0.0-beta2
`
And also edit the template inside the toolkit. The template path is $TOOLKIT_HOME/resources/templates/kubernetesDeployment.mustache.

Replace the content
`
{{#containerConfig.kubernetes.kubernetesDeployment.copyFiles.files}}
          {
            {{#if source}} source:"{{source}}", {{/if}}
            {{#if target}} target:"{{target}}", {{/if}}
            {{#if isBallerinaConf}} isBallerinaConf:{{isBallerinaConf}} {{/if}}
          }{{#unless @last}},{{/unless}}
      {{/containerConfig.kubernetes.kubernetesDeployment.copyFiles.files}}`

with the below content

`
{{#containerConfig.kubernetes.kubernetesDeployment.copyFiles.files}}
          {
            {{#if source}} source:"{{source}}", {{/if}}
            {{#if target}} target:"{{target}}" {{/if}}
          }{{#unless @last}},{{/unless}}
      {{/containerConfig.kubernetes.kubernetesDeployment.copyFiles.files}}`

We will fix the template and sample.yaml
