### ISSUE TITLE
After executing each command in toolkit suggest possible next step(s)

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-microgateway#686]
### Describe your problem(s)

Currently, after executing the commands only success message is displayed.
`micro-gw init petstore`
`Project 'petstore' is initialized successfully.`

### Describe your solution

`micro-gw init petstore`
`Project 'petstore' is initialized successfully.`
`Copy OAS to petstore/api_definition and build the project by issuing micro-gw build petstore or Import from WSO2 API Manager ..etc`

### How will you implement it

---

**Comment by praminda** [comment]
We only need these help messages for init and import commands.
I've added help message as in below screenshot. Format of the messages are inspired by `git` client's next step suggestions.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/2655553/65748080-b6960980-e120-11e9-90a2-f6f1060237e7.png">

Thoughts?

**Comment by Rajith90** [comment]
What about following guidelines
**Use "micro-gw build petstore" after copying the open API definitions to the api_definitions directory of the project**
What about changing the import help as below.
**"Use micro-gw import petstore -a <API_NAME> -v <API_VERSION>" to import APIs from WSO2 API Manager**
**Use "micro-gw import petstore -l <LABEL>" to import labeled APIs from WSO2 API Manager**

**Comment by praminda** [comment]
These messages are more like tips on what to do next. IMO it should answer **`what should I do next?`** question in user's mind. No need to give exact instructions **`how to do it`**. So we say **`use this command to continue`**. Its user's responsibility to find out the exact usage of the command and use it. Otherwise the tip become a guide. Which nearly duplicate the usage/help messages.

To make things clear on dev first approach how about this change
```diff
- Use "micro-gw build petstore" to build the project after adding APIs
+ Use "micro-gw build petstore" after copying the api definitions
```

Not mentioning the **openapi** since in future this can be any of openapi/grapqh/proto

What do you think?

**Comment by Rajith90** [comment]
+1, Lets give more insight about import command that it import APIs from WSO2 API Manager

**Comment by praminda** [comment]
```diff
- (Use "micro-gw import petstore" to import APIs)
+ (Use "micro-gw import petstore" to import APIs from WSO2 API Manager)

**Comment by praminda** [comment]
Fix is merged for next release branches. Hence closed the issue.
