### ISSUE TITLE
Microgateway doesn't work for SOAP backend services

### ISSUE THREAD

**Issue by harsha89** [wso2/product-microgateway#748]
### Description:
When micro gateway is created for a SOAP backend it's not working as request append with the "/" at the end of the url

### Steps to reproduce:
Create a microgateway using SOAP backend
Invoke it and check the behavior

### OS, DB, other environment details and versions:
- OS:
- Client:
- DB:
- Env (Docker/K8s):

---

**Comment by praminda** [comment]
This is caused by the fix we have introduced for #575. 
Specifically validating the case of `urlPostfix == ""` in [1] should fix the issue.

[1]: https://github.com/wso2/product-microgateway/blob/v3.0.1/components/micro-gateway-cli/src/main/resources/templates/service.mustache#L90 should fix the issue.
