### ISSUE TITLE
Can not add a new extension to the Micro Gateway toolkit

### ISSUE THREAD

**Issue by Prabhashi** [wso2/product-microgateway#764]
### Description
When a new extension file copy to the micro gateway toolkit resources/filters, it doesn't apply to the project.

### Steps to reproduce
1. Copy the extension file to the path <Micro-gw-toolkit_home>/resources/filters
2. Init the project 
3. Go to the extension location which is your-project-location/extensions
4. Check the added extension

### Product version
wso2am-micro-gw-toolkit-3.0.1

**Comment by praminda** [comment]
Hi @Prabhashi I don't see a valid use case for copying all filter resources in `TOOLKIT` to each project.

However it looks like we are not taking any additional filters provided in project's `extensions` directory at the `micro-gw build` command. This should be fixed so that any extensions provided in project is included in the built runtime artifact. I'll send a PR with a fix for that.
