### ISSUE TITLE
ProxyHandler  doesn't allow hostname in initial CONNECT request

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-microgateway#875]
### Description:
The HttpProxyHandler should include the hostname of the requested site in its initial CONNECT request.
When connecting through a proxy in Ballerina, for https proxy tunnelling, the first Connect request contains the IP address as the host. This can lead to policy failures in proxies like squid.

### Affected Product Version:
Api-Micro-GW 3.0.1/ 3.0.2

**Comment by Rajith90** [comment]
The issue here is when we try to connect to a backend via a proxy server like squid using the mgw
The microgateway 3.0.2 uses an old netty version. So when we use a proxy like squid with ssl bumping enabled , microgateway tries to search for the public cert of the proxy in its trust store. Ideally mgw should not validate proxy certificate. It should only validate the back end certificate. 

This was fixed in latest netty versions. Issue is explained in here [1]

[1] - https://github.com/netty/netty/issues/7668

**Comment by praminda** [comment]
@Rajith90 Is this fixed in master with jballerina upgrade. If so please close the issue.
