### ISSUE TITLE
Not able to redirect a request to an endpoint using interceptor or open api definition

### ISSUE THREAD

**Issue by skz363** [wso2/product-microgateway#928]
### Description:
We are using open API definition and interceptors to make request to dedicated backend but we are unable to make request to an endpoint other than that mentioned in the open API definition.
Is there a way to update the requested url through the Request object in the interceptor or the open API definition so that the end URL that is being hit is different from that mentioned in the open API definition.

### Steps to reproduce:
Attaching code:
OPEN API :
x-wso2-basePath: /Mobiquity/1.0.0
x-wso2-request-interceptor: validateGlobalRequest
x-wso2-response-interceptor: validateGlobalResponse
x-wso2-production-endpoints:
        urls:
        - http://localhost:7099/Mobiquity/      		
paths:
  "/callJigsaw/V2":
    post:
      tags:
      - callJigsaw
      summary: check for update
      description: callJigsaw
      operationId: callJigsaw
      x-wso2-request-interceptor: validateRequestDemo
      x-wso2-response-interceptor: validateResponse
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
      x-wso2-disable-security: true
"/callService/V2":
    post:
      tags:
      - callService
      summary: callService
      description: callService
      operationId: callService
      x-wso2-request-interceptor: validateRequestDemo
      x-wso2-response-interceptor: validateResponse
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
      x-wso2-disable-security: true
For example considering the above open API : if call comes to /Mobiquity/1.0.0/callJigsaw/V2 then the endpoint that is hit is http://localhost:7099/Mobiquity/callJigsaw/V2 but what i want is the endpoint should be changed dynamically to http://localhost:7099/Mobiquity/callService/V2 or may be any url that i have written in the **interceptor** through the request object
public function validateRequest (http:Caller outboundEp, http:Request req) {
    // Backend requires X-API-KEY header. No point in passing the request to the backend
    // if the header is not present in the request.
    boolean hasApiKey = req.hasHeader("token");
    if (!hasApiKey) {
        http:Response res = new;
        res.statusCode = 400;
		json message ={"serviceResponse":{"COMMAND":{"TYPE":"GENERAL","TXNSTATUS":"400","MESSAGE":"Missing required header","TXNMESSAGE":"Missing required header"}}};
        res.setPayload(message);
        var status = outboundEp->respond(res);
    } else {
	//set your url here that should ovveride the url defined in the callJigsaw path
	req.setUrl("http://your own url");
}
}
### Affected Product Version:

3.0.2
### Environment details (with versions):
- OS: windows
- Client:
- Env (Docker/K8s):

---

**Comment by Rajith90** [comment]
HI @skz363 
You can send the request to a different endpoint from the request interceptor . But in the default behaviour it will send two requests , one for the endpoint mentioned in the interceptor and one for the endpoint mentioned in the open API.
We can avoid this and achieve the expected behaviour by doing some modification to the template files of the toolkit.

Please edit the service.mustache (wso2am-micro-gw-toolkit-3.0.2/resources/templates/service.mustache) add the content [1] below the line[2].
This will stop sending request to the default back end.

Then in the request interceptor add the following line [3]

[1] - 
`
if(runtime:getInvocationContext().attributes.hasKey("breakRequestFlow")){
            if(<boolean>runtime:getInvocationContext().attributes["breakRequestFlow"]){
                return;
            }
        }
`
[2] - https://github.com/wso2/product-microgateway/blob/v3.0.4/components/micro-gateway-cli/src/main/resources/templates/service.mustache#L87

[3] -
`
runtime:getInvocationContext().attributes["breakRequestFlow"] = true;

`

**Comment by skz363** [comment]
closing this issue as it is solved with the solution suggested
