### ISSUE TITLE
Scope validation when basic authentication

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#958]
### Describe your problem(s)

API Manager 3.0.0 provides scope validation for basic authentication. Furthermore, scopes would be a great addition to authentication.

### Describe your solution

Note that in oas3.0 spec it says, Scopes are used only for OAuth 2 and OpenID Connect Discovery; other security schemes use an empty array [] instead. 
As a workaround, we can introduce an extension x-basic-auth-scopes.

### How will you implement it

---

**Comment by Rajith90** [comment]
related to #1103

**Comment by Rajith90** [comment]
FIxed in: https://mg.docs.wso2.com/en/latest/how-tos/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-jwt-self-contained-jwt/
https://mg.docs.wso2.com/en/latest/how-tos/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-opaque-tokens/
