### ISSUE TITLE
Rename micro-gw-default.conf template and Refactor code

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#972]
### Describe your problem(s)

micro-gw-default.conf file can be confused with micro-gw.conf file. The name should convey the message that it is not meant to be edited but it is only a template.
tokenservice template should properly log errors.
apikey test should be added to testng

### How will you implement it

Rename micro-gw-default.conf to default-micro-gw.conf.template. 

---

**Comment by praminda** [comment]
I'd also rename the `micro-gw.conf.template` file to something that doesn't start with `micro-...`. While working with a distribution which has this default conf file I notice it mess up the linux terminal autocompletion. Because there are two files starting with term `micro`. So shall we rename the default file to start with something else other that `micro`.

**Comment by praminda** [comment]
Also `Improvements` is not a good title for a issue 😃

**Comment by AmaliMatharaarachchi** [comment]
@praminda @Rajith90 How about the name default-micro-gw.conf.template? The name should indicate the association with the micro-gw.conf file too.
